parentPath = tagPath[:(tagPath.find('/')+1)]	
tags = system.tag.browse(parentPath + 'TestData')		
tagPaths = []
columnNames = ""
valuesWildCard = ""
values = []
						
for tag in tags:
	if 'LeakDetectionData' not in str(tag['fullPath']) and 'SaveData' not in str(tag['fullPath']):
		tagPaths.append(str(tag['fullPath']))	
		columnNames = columnNames + str(tag['name']) + ','
columnNames = columnNames[:-1]							
qualityValues = system.tag.readBlocking(tagPaths)
				
for i in qualityValues:
	values.append(i.value)
				
for value in values:
	valuesWildCard += '?,'
valuesWildCard = valuesWildCard[:-1]		
				
query = "INSERT INTO testdata ({}) VALUES ({})".format(columnNames, valuesWildCard)		
autoGeneratedIndex = system.db.runPrepUpdate(query=query, args=values, database="testdata", getKey=True)
		
#---------------------------------------------------------------------------------------------------------------------
		
tags = system.tag.browse(parentPath + 'TestData/LeakDetectionData')		
tagPaths = []
columnNames = ""
valuesWildCard = ""
values = []
								
for tag in tags:
	tagPaths.append(str(tag['fullPath']))	
	columnNames = columnNames + str(tag['name']) + ','
columnNames = columnNames[:-1]							
qualityValues = system.tag.readBlocking(tagPaths)
						
for i in qualityValues:
	values.append(i.value)
						
for value in values:
	valuesWildCard += '?,'
valuesWildCard = valuesWildCard[:-1]	
valuesWildCard = valuesWildCard + ',?'
columnNames = 'testdata_id,' + columnNames
values.insert(0, autoGeneratedIndex)	
						
query = "INSERT INTO leak_detection_data ({}) VALUES ({})".format(columnNames, valuesWildCard)		
update = system.db.runPrepUpdate(query=query, args=values, database="testdata", getKey=True)